apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsveiviserproxy
  namespace: default
spec:
  image: navikt/soknadsveiviserproxy:latest
  team: teaminformasjonogveiledning
  port: 80
  healthcheck:
    liveness:
      path: /isAlive
      initialDelay: 20
    readiness:
      path: /isReady
initialDelay: 20
