# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/sbl/soknadsveiviserproxy
replicas:
  min: 1
  max: 2
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: soknadsveiviserproxy/isAlive
    initialDelay: 20
  readiness:
    path: soknadsveiviserproxy/isReady
    initialDelay: 20
