---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{reponame}}
  namespace: default
  labels:
    team: {{team}}
spec:
  image: navikt/{{reponame}}:{{version}}
  team: {{team}}
  port: 8080
  ingresses:
    - {{ingress1}}
    - {{ingress2}}
  liveness:
    path: {{baseurl}}/internal/isAlive
    initialDelay: 10
  readiness:
    path: {{baseurl}}/internal/isReady
    initialDelay: 10
  vault:
    enabled: true
  replicas:
    min: 2
    max: 6
  webproxy: true
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/etc/ssl/ca-bundle.pem"
  resources:
    limits:
      cpu: '3' # app will have its cpu usage throttled if exceeding this limit
      memory: 2Gi  # app will be killed if exceeding these limits
    requests: # app will be scheduled on nodes with at least this amount resources available
      cpu: '1.5'
      memory: 2Gi
