---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: soknadsveiviserproxy
  namespace: {{namespace}}
  labels:
    team: skjemadigitalisering
spec:
  image: {{image}}:{{version}}
  team: skjemadigitalisering
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /soknadsveiviserproxy/internal/isAlive
    initialDelay: 10
  readiness:
    path: /soknadsveiviserproxy/internal/isReady
    initialDelay: 10
  vault:
    enabled: true
  prometheus:
    enabled: true
    path: /soknadsveiviserproxy/metrics
  replicas:
    min: 3
    max: 6
  webproxy: true
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/etc/ssl/ca-bundle.pem"
  resources:
    limits:
      cpu: '3'
      memory: 768Mi
    requests:
      memory: 512Mi
