---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: soknadsveiviserproxy
  namespace: {{NAMESPACE}}
  labels:
    team: skjemadigitalisering
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each INGRESSES as |url|}}
     - {{url}}
  {{/each}}
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: soknadsveiviser
    outbound:
      external: 
      {{#each EXTERNAL_HOSTS as |url|}}
        - host: {{url}}
      {{/each}}
  liveness:
    path: /soknadsveiviserproxy/internal/isAlive
    initialDelay: 10
  readiness:
    path: /soknadsveiviserproxy/internal/isReady
    initialDelay: 10
  replicas:
    min: 3
    max: 6
  webproxy: true
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/etc/ssl/ca-bundle.pem"
  envFrom:
    - secret: soknadsveiviserproxy
  resources:
    limits:
      cpu: '3'
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
