name: "Build and deploy"
on:
  pull_request:
  push:
    branches:
      - master
env:
  CI: "true"
  IMAGE_REGISTRY: docker.pkg.github.com/${{ github.repository }}
  IMAGE_VERSION: ${{ github.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPO: ${{ github.repository }}
  IMAGE_NAME: soknadsveiviserproxy

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm test
      - name: Docker build and push
        run: |
          echo ${GITHUB_TOKEN} | docker login --username ${GITHUB_REPO} --password-stdin https://docker.pkg.github.com
          docker build --pull --tag ${IMAGE_REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION} .
          docker push ${IMAGE_REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: build-and-package
    steps:
      - uses: actions/checkout@v1
      - name: Generate nais variables
        run: |
          cat > .nais/vars.yaml <<EOF
          namespace: skjemadigitalisering
          ingresses:
            - https://tjenester-q0.nav.no/soknadsveiviserproxy
            - https://soknadsveiviserproxy.dev.nav.no
          image: $IMAGE_REGISTRY/$IMAGE_NAME
          version: $IMAGE_VERSION
          EOF
      - uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-sbs
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yaml
          VARS: .nais/vars.yaml

  deploy-to-prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    steps:
      - uses: actions/checkout@v1
      - name: Generate nais variables
        run: |
          cat > .nais/vars.yaml <<EOF
          namespace: skjemadigitalisering
          ingresses:
            - https://soknadsveiviserproxy.nais.oera.no
            - https://tjenester.nav.no/soknadsveiviserproxy
          image: $IMAGE_REGISTRY/$IMAGE_NAME
          version: $IMAGE_VERSION
          EOF
      - uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: prod-sbs
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yaml
          VARS: .nais/vars.yaml
